version = 3
root = "/var/lib/sandcube-containerd"
state = "/run/sandcube-containerd"
disabled_plugins = ["io.containerd.grpc.v1.cri", "io.containerd.cri.v1.images", "io.containerd.cri.v1.runtime"]
[grpc]
  address = "/run/sandcube-containerd/containerd.sock"
